[build]
    command = "npm run build"
    publish = "dist/lims-toolbox/browser"
    functions = "netlify/functions"

[[redirects]]
    from = "/"
    to = "/home"
    status = 302

    from = "/*"
    to = "/index.html"
    status = 200