version: 0.1

phases:
  install:
    commands:
      - echo Installing Docker
      - apt-get update
      - apt-get install -y docker.io
      - echo Logging in to Docker Hub
      - echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin

  build:
    commands:
      - echo Building Docker image
      - cd backend && docker build -t toolbox-deployment .
      - docker images
      - echo Pushing Docker image to Docker Hub
      - docker tag toolbox-deployment limlei2/toolbox-deployment:latest
      - docker push limlei2/toolbox-deployment:latest

  post_build:
    commands:
      - echo Build completed on `date`