version: 0.1

phases:
  install:
    commands:
      - echo Installing Docker
      - apt-get update
      - apt-get install -y docker.io
      - echo Logging in to Docker Hub
      - echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin

  build:
    commands:
      - echo Building Docker image
      - cd backend
      - mvn clean install -DskipTests
      - docker build -t $IMAGE_NAME:$IMAGE_TAG .
      - echo Pushing Docker image to Docker Hub
      - docker push $IMAGE_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`